### ISSUE TITLE
Could not pass event PlayerDeathEvent to DeathMessages - FallingBlock

### ISSUE THREAD

**Issue by gamerover98** [HMJosh/DeathMessages#1]
## Version
kSpigot (a paper fork) 1.12.2

## Logs
```
[05:23:22 ERROR]: Could not pass event PlayerDeathEvent to DeathMessages v1.3.0
java.lang.NoSuchMethodError: 'org.bukkit.block.data.BlockData org.bukkit.entity.FallingBlock.getBlockData()'
        at net.joshb.deathmessages.assets.Assets.getNaturalDeath(Assets.java:247) ~[?:?]
        at net.joshb.deathmessages.listener.EntityDeath.onEntityDeath(EntityDeath.java:80) ~[?:?]
        at net.joshb.deathmessages.listener.EntityDeath.onEntityDeath_HIGH(EntityDeath.java:180) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor27.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[kSpigot.jar:git-Paper-33d42c8e]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[kSpigot.jar:git-Paper-33d42c8e]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[kSpigot.jar:git-Paper-33d42c8e]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[kSpigot.jar:git-Paper-33d42c8e]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:422) ~[kSpigot.jar:git-Paper-33d42c8e]
        at net.minecraft.server.v1_12_R1.EntityPlayer.die(EntityPlayer.java:463) ~[kSpigot.jar:git-Paper-33d42c8e]
        at net.minecraft.server.v1_12_R1.EntityLiving.damageEntity(EntityLiving.java:983) ~[kSpigot.jar:git-Paper-33d42c8e]
        at net.minecraft.server.v1_12_R1.EntityHuman.damageEntity(EntityHuman.java:777) ~[kSpigot.jar:git-Paper-33d42c8e]
        at net.minecraft.server.v1_12_R1.EntityPlayer.damageEntity(EntityPlayer.java:629) ~[kSpigot.jar:git-Paper-33d42c8e]
        at net.minecraft.server.v1_12_R1.EntityFallingBlock.e(EntityFallingBlock.java:227) ~[kSpigot.jar:git-Paper-33d42c8e]
        at net.minecraft.server.v1_12_R1.Block.fallOn(Block.java:542) ~[kSpigot.jar:git-Paper-33d42c8e]
        at net.minecraft.server.v1_12_R1.Entity.a(Entity.java:1086) ~[kSpigot.jar:git-Paper-33d42c8e]
        at net.minecraft.server.v1_12_R1.Entity.move(Entity.java:868) ~[kSpigot.jar:git-Paper-33d42c8e]
        at net.minecraft.server.v1_12_R1.EntityFallingBlock.B_(EntityFallingBlock.java:88) ~[kSpigot.jar:git-Paper-33d42c8e]
        at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1797) ~[kSpigot.jar:git-Paper-33d42c8e]
        at net.minecraft.server.v1_12_R1.World.h(World.java:1767) ~[kSpigot.jar:git-Paper-33d42c8e]
        at net.minecraft.server.v1_12_R1.World.tickEntities(World.java:1574) ~[kSpigot.jar:git-Paper-33d42c8e]
        at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(WorldServer.java:682) ~[kSpigot.jar:git-Paper-33d42c8e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:933) ~[kSpigot.jar:git-Paper-33d42c8e]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[kSpigot.jar:git-Paper-33d42c8e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:786) ~[kSpigot.jar:git-Paper-33d42c8e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:678) ~[kSpigot.jar:git-Paper-33d42c8e]
        at java.lang.Thread.run(Thread.java:832) [?:?]
```

## Description

When the player is killed by a falling block, the method getBlockData() that returns org.bukkit.data.BlockData doesn't exist.
BlockData class was added in 1.13 so, under versions doesn't support this method.

# Ipotetic resolution

Create two maven modules:
1. The legacy module for 1.8 to 1.12.2 stuff.
2. The flattening module for 1.13+ staff.

I'll fix this issue temporarily by edit it to guarantee the legacy working.

**Comment by HMJosh** [comment]
I do not provide support here. Take it to spigot MC or https://discord.gg/K9zVDwt
